const url = {
    development: {
        targetUrl: 'https://homefair-dev.bnq.com.cn',
        apiUrl: 'http://web.futureshop.dev-zt.bnq.com.cn:8016',
        apiUrlFilter: '/dcmall-api-server',
        authUrl: 'http://auth-dev.bnq.com.cn',
        authUrlFilter: '/auth',
        port: 8016,
        autoOpenBrowser: true,
        proxyFilter: '/dcmall-api-server',
        locationApi: 'https://homefair-dev.bnq.com.cn',
        locationUrl: 'http://web.futureshop.dev-zt.bnq.com.cn:8016',
        locationFilter: '/bnq_owner',
        skuApi: 'https://item.bnq.com.cn',
        skuUrl: 'http://web.futureshop.dev-zt.bnq.com.cn:8016',
        skuFilter: '/items',
        qingmingApi: '//m.market.bnq.com.cn/wx-web',
        loginApi: '//m-dev.market.bnq.com.cn/wx-web',
        skuDetailApi: 'https://item.bnq.com.cn',
        skuDetailUrl: 'http://web.futureshop.dev-zt.bnq.com.cn:8016',
        skuDetailFilter: '/item',
        pageUrl: 'https://homefair-dev.bnq.com.cn',
    },
    prodDev: {
        apiUrl: 'https://homefair-dev.bnq.com.cn',
        apiUrlFilter: '/dcmall-api-server',
        locationUrl: 'https://homefair-dev.bnq.com.cn',
        locationFilter: '/bnq_owner',
        skuUrl: 'https://item.bnq.com.cn',
        skuFilter: '/items',
        qingmingApi: '//m.market.bnq.com.cn/wx-web',
        loginApi: '//m-dev.market.bnq.com.cn/wx-web',
        skuDetailUrl: 'https://item.bnq.com.cn',
        skuDetailFilter: '/item',
        authUrl: 'http://auth-dev.bnq.com.cn',
        authUrlFilter: '/auth',
        pageUrl: 'https://homefair-dev.bnq.com.cn',
    },
    test: {
        apiUrl: 'https://homefair-test.bnq.com.cn',
        apiUrlFilter: '/dcmall-api-server',
        locationUrl: 'https://homefair-test.bnq.com.cn',
        locationFilter: '/bnq_owner',
        skuUrl: 'https://item.bnq.com.cn',
        skuFilter: '/items',
        qingmingApi: '//m-test.market.bnq.com.cn/wx-web',
        loginApi: '//m-test.market.bnq.com.cn/wx-web',
        skuDetailUrl: 'https://item.bnq.com.cn',
        skuDetailFilter: '/item',
        authUrl: 'http://auth-test.bnq.com.cn',
        authUrlFilter: '/auth',
        pageUrl: 'https://homefair-test.bnq.com.cn',
    },
    production: {
        apiUrl: 'https://homefair.bnq.com.cn',
        apiUrlFilter: '/dcmall-api-server',
        locationUrl: 'https://homefair.bnq.com.cn',
        locationFilter: '/bnq_owner',
        skuUrl: 'https://item.bnq.com.cn',
        skuFilter: '/items',
        skuDetailUrl: 'https://item.bnq.com.cn',
        skuDetailFilter: '/item',
        qingmingApi: '//m.market.bnq.com.cn/wx-web',
        loginApi: '//m.market.bnq.com.cn/wx-web',
        authUrl: 'http://auth.bnq.com.cn',
        authUrlFilter: '/auth',
        pageUrl: 'https://homefair.bnq.com.cn',
    },
};

module.exports = url;
