const url = {
    development: {
        targetUrl: 'https://demo-dev.demo.com.cn',
        apiUrl: 'http://web.futureshop.dev-zt.demo.com.cn:8016',
        apiUrlFilter: '/demo-api-server',
        demoUrl: 'http://demo-dev.demo.com.cn',
        demoUrlFilter: '/demo',
        port: 8016,
        autoOpenBrowser: true,
        proxyFilter: '/demo-api-server',
        locationApi: 'https://demo-dev.demo.com.cn',
        locationUrl: 'http://web.futureshop.dev-zt.demo.com.cn:8016',
        locationFilter: '/demo_owner',
        skuApi: 'https://demo.demo.com.cn',
        skuUrl: 'http://web.futureshop.dev-zt.demo.com.cn:8016',
        skuFilter: '/demos',
        qingmingApi: '//m.demo.demo.com.cn/wx-web',
        loginApi: '//m-dev.demo.demo.com.cn/wx-web',
        skuDetailApi: 'https://demo.demo.com.cn',
        skuDetailUrl: 'http://web.futureshop.dev-zt.demo.com.cn:8016',
        skuDetailFilter: '/demo',
        pageUrl: 'https://demo-dev.demo.com.cn',
    },
    prodDev: {
        apiUrl: 'https://demo-dev.demo.com.cn',
        apiUrlFilter: '/demo-api-server',
        locationUrl: 'https://demo-dev.demo.com.cn',
        locationFilter: '/demo_owner',
        skuUrl: 'https://demo.demo.com.cn',
        skuFilter: '/demos',
        qingmingApi: '//m.demo.demo.com.cn/wx-web',
        loginApi: '//m-dev.demo.demo.com.cn/wx-web',
        skuDetailUrl: 'https://demo.demo.com.cn',
        skuDetailFilter: '/demo',
        demoUrl: 'http://demo-dev.demo.com.cn',
        demoUrlFilter: '/demo',
        pageUrl: 'https://demo-dev.demo.com.cn',
    },
    test: {
        apiUrl: 'https://demo-test.demo.com.cn',
        apiUrlFilter: '/demo-api-server',
        locationUrl: 'https://demo-test.demo.com.cn',
        locationFilter: '/demo_owner',
        skuUrl: 'https://demo.demo.com.cn',
        skuFilter: '/demos',
        qingmingApi: '//m-test.demo.demo.com.cn/wx-web',
        loginApi: '//m-test.demo.demo.com.cn/wx-web',
        skuDetailUrl: 'https://demo.demo.com.cn',
        skuDetailFilter: '/demo',
        demoUrl: 'http://demo-test.demo.com.cn',
        demoUrlFilter: '/demo',
        pageUrl: 'https://demo-test.demo.com.cn',
    },
    production: {
        apiUrl: 'https://demo.demo.com.cn',
        apiUrlFilter: '/demo-api-server',
        locationUrl: 'https://demo.demo.com.cn',
        locationFilter: '/demo_owner',
        skuUrl: 'https://demo.demo.com.cn',
        skuFilter: '/demos',
        skuDetailUrl: 'https://demo.demo.com.cn',
        skuDetailFilter: '/demo',
        qingmingApi: '//m.demo.demo.com.cn/wx-web',
        loginApi: '//m.demo.demo.com.cn/wx-web',
        demoUrl: 'http://demo.demo.com.cn',
        demoUrlFilter: '/demo',
        pageUrl: 'https://demo.demo.com.cn',
    },
};

module.exports = url;
